input {
  beats { port => 5045 }
}

filter {
  if [service] {
    mutate { add_field => { "[@metadata][index]" => "nt219-%{[service]}-%{+YYYY.MM.dd}" } }
  } else {
    mutate { add_field => { "[@metadata][index]" => "nt219-misc-%{+YYYY.MM.dd}" } }
  }

  if [type] == "vault-audit" {
    json { source => "message" target => "vault" }
    mutate { add_tag => ["vault-audit"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}"
  }
}
